// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Xha57ZzGMG7LECuL-BBWktdZkA5jB9w',
    appId: '1:393943450881:web:096295318582bd02f78700',
    messagingSenderId: '393943450881',
    projectId: 'openwhen-923f5',
    authDomain: 'openwhen-923f5.firebaseapp.com',
    storageBucket: 'openwhen-923f5.firebasestorage.app',
    measurementId: 'G-3499DN7B5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHKuny9dRSaNUs2Yr30PWAZfMRP9jGyxw',
    appId: '1:393943450881:android:d59614a57968e7bcf78700',
    messagingSenderId: '393943450881',
    projectId: 'openwhen-923f5',
    storageBucket: 'openwhen-923f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtOU1vrWy3bvVuK08g0CkgkuFoxQ7_tHs',
    appId: '1:393943450881:ios:2246a39942ff595ff78700',
    messagingSenderId: '393943450881',
    projectId: 'openwhen-923f5',
    storageBucket: 'openwhen-923f5.firebasestorage.app',
    iosBundleId: 'com.example.openwhen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtOU1vrWy3bvVuK08g0CkgkuFoxQ7_tHs',
    appId: '1:393943450881:ios:2246a39942ff595ff78700',
    messagingSenderId: '393943450881',
    projectId: 'openwhen-923f5',
    storageBucket: 'openwhen-923f5.firebasestorage.app',
    iosBundleId: 'com.example.openwhen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5Xha57ZzGMG7LECuL-BBWktdZkA5jB9w',
    appId: '1:393943450881:web:c4e98d607f2d2d69f78700',
    messagingSenderId: '393943450881',
    projectId: 'openwhen-923f5',
    authDomain: 'openwhen-923f5.firebaseapp.com',
    storageBucket: 'openwhen-923f5.firebasestorage.app',
    measurementId: 'G-18MPNKK07T',
  );
}
